project:
  type: website

website:
  title: "Diesel Mears Research Notebook"
  site-url: "https://1dzl0.github.io/research-notebook/"

  navbar:
    background: light
    foreground: "#0F172A"
    left:
      - href: index.qmd
        text: Home

      - text: Research
        menu:
          - text: Research Development
            href: 00-research/research-development.qmd
          - text: Research Questions
            href: 00-research/research-questions.qmd
          - text: Roadmap
            href: 00-research/research-roadmap.qmd

      - text: Literature
        menu:
          - text: Literature Map
            href: 01-literature/literature-map.qmd
          - text: Papers
            href: 01-literature/papers.qmd

      - text: Projects
        menu:
          - text: Pharos-CY
            href: 02-projects/pharos-cy.qmd
          - text: GenAI4ED
            href: 02-projects/genai4ed.qmd

      - text: Experiments
        menu:
          - text: Prisoner's Dilemma
            href: 03-experiments/prisoners-dilemma.qmd


      - text: Meetings
        href: 04-meetings/supervisor.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header: mermaid-init.html
